name: Run Cowsay Script

on:
  push
  

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: display
        run : echo $USERNAME
    
  # job:
  #   runs-on: ubuntu-latest

  #   steps:
  #     # Checkout the repository
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     # Set up the environment
  #     - name: Install Cowsay
  #       run: sudo apt update && sudo apt install -y cowsay

  #     # Run the cowsay script
  #     - name: Run cowsay_script.sh
  #       run: |
  #         chmod +x scripts.sh
  #         ./scripts.sh
  #     - name: upload
  #       uses: actions/upload-artifact@v4
  #       with:
  #           name: drago1
  #           path: ./drago.txt
  # job1:
  #   runs-on: ubuntu-latest

  #   steps:
  #     # Checkout the repository
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     # Set up the environment
  #     - name: Install Cowsay
  #       run: sudo apt update && sudo apt install -y cowsay

  #     # Run the cowsay script
  #     - name: Run cowsay_script.sh
  #       run: |
  #         chmod +x scripts.sh
  #         ./scripts.sh
  #     - name: upload
  #       uses: actions/upload-artifact@v4
  #       with:
  #           name: drago
  #           path: ./drago.txt
  # test:
  #   runs-on: ubuntu-latest
  #   needs: [job,job1]
  #   steps:
  #     # Checkout the repository
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: download
  #       uses: actions/download-artifact@v4
  #       with: 
  #         name: drago
  #     - name: display
  #       run : |
  #         echo $USERNAME
  #         cat drago.txt
  