name: Run Cowsay Script

on: push

jobs:
  cowsay_job:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the environment
      - name: Install Cowsay
        run: sudo apt update && sudo apt install -y cowsay

      # Run the cowsay script
      - name: Run cowsay_script.sh
        run: |
          chmod +x scripts.sh
          ./scripts.sh
