name: Run Cowsay Script

on: push

jobs:
  cowsay_job:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the environment
      - name: Install Cowsay
        run: sudo apt update && sudo apt install -y cowsay

      # Run the cowsay script
      - name: Run cowsay_script.sh
        run: |
          chmod +x scripts.sh
          ./scripts.sh
      - name: upload
        uses: actions/upload-artifact@v4
        with:
            name: drago
            path: /drago.txt
  test:
    runs-on: ubuntu-latest
    needs: cowsay_job
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      - name: download
        uses: actions/download-artifact@v4
        with: 
          name: drago.txt