name: checking if

on:
  push

jobs:
    check-condition:
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - name : "printing"
              run : echo "condition True"
    next-job:
        # needs: check-condition
        runs-on: ubuntu-latest
        steps:
            - name: "next"
              run : echo "next running in master"
  
